name: Add Git Trailers to PR commits

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  git-trailers:
    name: Add Git Trailers to PR commits
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.review.state == 'approved' }}
    uses: ./.github/workflows/add-git-trailers.yml
    secrets: inherit
